### ISSUE TITLE
Screenshot Error

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/use-all-the-selectors#1]
My CSS is too visually different from the screenshot (23% difference; need 13%). I don't know how to reduce this number! Please help

@hellachella @carolsinc

**Comment by carolsinc** [comment]
Markbot screen shots are especially sensitive to colour. Look at your headers and Types of Simple Fruit list

**Comment by carolsinc** [comment]
When using nth child you need to be more specific and target the li 
.types li:nth-child(odd)

**Comment by emahadzimustafic** [comment]
Thanks for the help!
